### PR TITLE
Refactor project structure

### PR DESCRIPTION
**Pull request by lucamonfredo**
Hello!

As we said in the [roadmap discussion](https://github.com/EdNekebno/DGTCentaur/discussions/12), I began to work on giving a little structure to the project files, because as we move forward it's easy to complicate things 😉 

I reorganized the files in sub-packages and added some directories to contain compiled code (`bin`), resources (`resources`) and various scripts (`scripts`).

In `scripts` I have stubbed an installation script which could be a starting point to link the various files around without having to copy them.

I'm pushing the branch in this incomplete state because I know that you are already working on other features, with the hope that we can merge our works on a common line of development before it's too late 😄

We should start working on an installation script that starts from a basic Raspbian lite installation and makes everything work (i.e. by installing packages and / or connecting the various scripts), in order to make the work environment reproducible between us and have a common ground.

While you concentrate on the new features (BT, Lichess, etc ..) I can possibly try to deal with them. 

Let me know, thank you!

### CODE REVIEW

**Comment by EdNekebno** [comment]
Looks great. I also really like the idea of the installation script.

But I think my python newness is getting in the way...you might need to teach me! I have virtually zero understanding of packages and things.

This then sits in /home/pi/mods ?

If I put it there or symlink it in then it tells me it can't find the module dgt_centaur_mods . 

 from dgt_centaur_mods import boardfunctions
ModuleNotFoundError: No module named 'dgt_centaur_mods'

Must I put it somewhere particular for python to find it as a module?

**Comment by lucamonfredo** [comment]
Well, my fault 😅 I told you that this is incomplete...

It appears you don't have the directory tracked in your `PYTHONPATH` env var.
Assuming you have cloned the repo in `/home/pi/DGTCentaur`, you just have to set or add it to PYTHONPATH, like this:

`export PYTHONPATH=${PYTHONPATH}:${HOME}/DGTCentaur`

I'll try to include it when I'll finish the initial install script, let me know if it's OK for you. Thanks Ed!

**Comment by EdNekebno** [comment]
Closer...

With the pythonpath it gave me an error message but a different one. Then my board rebooted and of course pythonpath was gone. Then I wondered if we'll always be calling python with a shell. So I cheated and just did: ln -s /home/pi/DGTCentaur/dgt_centaur_mods /usr/lib/python3/dist-packages/dgt_centaur_mods to symlink it into the path. 

I get this with both methods if I try to run the menu:

/usr/bin/python3.7 /home/pi/mods/game/menu.py
Traceback (most recent call last):
  File "/home/pi/mods/game/menu.py", line 3, in <module>
    from dgt_centaur_mods import boardfunctions
ImportError: cannot import name 'boardfunctions' from 'dgt_centaur_mods' (/usr/lib/python3/dist-packages/dgt_centaur_mods/__init__.py)

If I change it to board.boardfunctions it gets past that but later complains about the epdconfig file in epd2in9d.py:

File "/usr/lib/python3/dist-packages/dgt_centaur_mods/display/epd2in9d.py", line 34, in <module>
    import epdconfig

I'm not sure if python is supposed to recurse those folders and my setup still needs something, or if it's a case of updating each import instance in the files to add the folders?

**Comment by lucamonfredo** [comment]
There was an error in the import, I fixed that, sorry.
And yes, we should persist PYTHONPATH in the profile or something like that, but I wanted to give you a "quick" solution to test that everything was OK. I don't understand the reason for the reboot instead. Let me know if now it's better, thanks.

**Comment by EdNekebno** [comment]
Awesome, that's worked (I ended up symbolic linking in the python modules folder + in /home/pi/mods). It's awesome, thanks, I'll try not to make too much of a mess :)

**Comment by lucamonfredo** [comment]
Great!
Now we should have a starting point to keep things neat, I'll continue working on the install script and refining the "plumbing" stuff. Ideally the process would be: clone the repo somewhere on your pi, edit a config file and then launch the install script. Easier said than done, but let's try it 😃

**Pull request merged**
